nve:
  dt: 4.0
maxsteps: 1000000
batch_size: 25
chunk_size: 25000
potential:
  mlff:
    folder: "../../../../model/"

calculator:
  atom_pair:
    heat_flux: True
    convective: True
    skin: 1.0

files:
  geometry: geometry.in
  supercell: geometry.in.supercell
  primitive: geometry.in.primitive